name: flutter_woocommerce
description: "WooClot – Flutter E‑Commerce UI with Cart, Wishlist, Orders, and smooth animations. Ready for CodeCanyon."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.1
  carousel_slider: ^5.1.1
  flutter_staggered_grid_view: ^0.7.0
  font_awesome_flutter: ^10.11.0
  provider: ^6.1.5+1
  pinput: ^5.0.2
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/core/
    - assets/dummy/


flutter_launcher_icons:
  image_path_android: "assets/launcher/icon.png"
  image_path_ios: "assets/launcher/icon.png"
  android: true
  ios: true
  adaptive_icon_background: "assets/launcher/bg.png"


  # example:
  fonts:
    - family: CircularStd
      fonts:
        - asset: assets/fonts/CircularStd-Black.ttf
        - asset: assets/fonts/CircularStd-BlackItalic.ttf
        - asset: assets/fonts/CircularStd-Bold.ttf
        - asset: assets/fonts/CircularStd-Book.ttf
        - asset: assets/fonts/CircularStd-Medium.ttf

  #
